Repository esse-dev/akita, pull requests merged in 2020-06, with the labels that each got.

#19 Reorganize project and make indentation consistent
  AkitaOriginData.js
  AkitaPaymentPointerData.js
  WebMonetizationAsset.js
  assets/icon.png
  example_data.json
  examples/example_data.json
  manifest.json
  src/background_script.js
  src/content_main.js
  src/data/AkitaOriginData.js
  src/data/AkitaPaymentPointerData.js
  src/data/WebMonetizationAsset.js
  src/data/storage.js
  src/popup/popup.html
  storage.js
Labels: sketchy

#21 Set Akita extension icon and extension badge based on the monetization of site
  assets/icon.png
  assets/icon.svg
  assets/icon_unmonetized.png
  src/background_script.js
  src/content_main.js
  src/popup/popup.html
Labels: GftW x DEV Hackathon, sketchy

#23 Track site visits and time spent on sites
  examples/example_data.json
  manifest.json
  src/content_main.js
  src/data/AkitaOriginData.js
  src/data/AkitaOriginVisitData.js
  src/data/AkitaPaymentPointerData.js
  src/data/WebMonetizationAsset.js
  src/data/storage.js
Labels: GftW x DEV Hackathon, sketchy

#24 Add Akita icons, expand README and include install steps
  README.md
  assets/icon_128x128.png
  assets/icon_16x16.png
  assets/icon_48x48.png
  assets/icon_64x64.png
  docs/InstallAkita.md
  manifest.json
Labels: GftW x DEV Hackathon, sketchy

#25 add chart.js library code and use it in popup.js
  library/chart.min.css
  library/chart.min.js
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#31 add slideshow and UI without wiring it up
  assets/coil_logo.svg
  assets/disapointed_toaster.svg
  assets/puma-logo.svg
  assets/wm-icon-animated.svg
  library/flickity.css
  library/flickity.min.js
  src/popup/popup.html
  src/popup/popup.js
Labels: sketchy

#32 Add various calculations to use in UI display
  README.md
  examples/example_data.json
  manifest.json
  src/background_script.js
  src/content_main.js
  src/data/AkitaOriginData.js
  src/data/AkitaOriginStats.js
  src/data/AkitaOriginVisitData.js
  src/data/AkitaPaymentPointerData.js
  src/data/WebMonetizationAsset.js
  src/data/storage.js
  src/main.js
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#36 Wiring
  manifest.json
  src/background_script.js
  src/content_main.js
  src/main.js
  src/popup/popup.html
  src/popup/popup.js
Labels: sketchy

#37 final hackathon commit
  assets/demo_mon.png
  assets/demo_unmon.png
  library/chart.min.css
  library/chart.min.js
  src/background_script.js
  src/content_main.js
  src/popup/popup.html
  src/popup/popup.js
Labels: sketchy

#38 final hackathon commit for real this time
  src/popup/popup.html
  src/popup/popup.js
Labels: sketchy

#42 small improvements made during code walkthrough
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon

#44 Add favicons to needslove, custom bullets, link colour matches branding
  examples/example_data.json
  manifest.json
  src/background_script.js
  src/content_main.js
  src/data/AkitaOriginData.js
  src/data/storage.js
  src/main.js
  src/popup/popup.css
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#45 Retrieve origin favicons and add percent metrics to top site detail
  src/main.js
  src/popup/popup.css
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#47 Improve popup data
  src/main.js
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#49 add custom css tooltip and fix some issues
  library/flickity.css
  src/popup/popup.css
  src/popup/popup.html
  src/popup/popup.js
Labels: sketchy

#51 Fix various bugs discovered in #48 testing
  src/content_main.js
  src/data/storage.js
  src/main.js
  src/popup/popup.css
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#52 Allow already resolved payment pointer (https prefix)
  src/content_main.js
Labels: GftW x DEV Hackathon

#53 Hide needs love by default until monetized site visited
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#56 add sleep akita placeholder illustration
  assets/sleepy_akita.svg
  src/popup/popup.css
  src/popup/popup.html
  src/popup/popup.js
Labels: sketchy

#57 Fix double link and buggy smooth scroll on firefox
  src/main.js
  src/popup/popup.css
  src/popup/popup.html
  src/popup/popup.js
Labels: GftW x DEV Hackathon, sketchy

#59 Add screenshots/demo and contributing info to README
  CONTRIBUTING.md
  README.md
  assets/akita_social_preview.png
  assets/icon_1024x1024.png
  assets/mon_demo_screenshot.png
  assets/needslove_demo_screenshot.png
  assets/nonmon_demo_screenshot.png
Labels: GftW x DEV Hackathon, sketchy

#61 Add Akita walkthrough YouTube link
  README.md
Labels: GftW x DEV Hackathon
